version: "3"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx:1.25.1-alpine3.17-slim
    ports:
#      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/:/etc/ssl/private
#    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
