version: '3.9'
services:
  db:
    image: postgres:11
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
    volumes:
      - pwc-jacademy-postgresql11-data:/var/lib/postgresql/data:z
volumes:
  pwc-jacademy-postgresql11-data:
